$ANSIBLE_VAULT;1.1;AES256
39643665366332666361623866653334333962663861326237313963363230356335633735653864
3662643763633133366331343863656230643663636638610a303331316331306137393134306433
38663333343933303133313566613739623730336662643364633033366235636531333837396365
6561613038663339310a393364633536333561643334346132336133373565646230313436656265
37383035636462386565663336353262646638333063343931656232663736383066393833363434
34343864336565616337323365333633396531326532383763373066613732393465326530313230
66316165353038653034333264633038303262363730633965613639393061353236663263616434
65613332376666356335316433623530336430323530633532633230613536303138333930656639
3933
